Add support for spring-boot-docker-compose
spring-io/initializr pull request #1406
Opened 2023-04-28 13:01 UTC by mhalbritter

Adds `DockerComposeGradleBuildCustomizer` and `DockerComposeMavenBuildCustomizer`, which sets `developmentOnly` or `<optional>true</optional>` for the `spring-boot-docker-compose` dependency.

2023-04-28 13:40 UTC, mhalbritter commented
Unsure why the build fails. It works locally when using `clean install`. I can't see the details if the concourse job, it never stops showing the loading spinner.

2023-04-28 13:47 UTC, wilkinsona commented
It might be a permissions problem as I can see the logs. The failure was the following:

```
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.7:wget (unpack-doc-resources) on project initializr-docs: IO Error: Error while expanding /tmp/build/6da1d659/git-repo/initializr-docs/target/refdocs/spring-doc-resources-0.2.2.RELEASE.zip: Archive is not a ZIP archive -> [Help 1]
```

That looks like a corrupted zip download unrelated to your changes.

2023-05-02 07:12 UTC, wilkinsona commented
@mhalbritter Could you please rebase and force-push. I believe the problem that caused your build to fail on CI has been fixed by the changes that have been made thus far for #1408.

2023-05-23 13:53 UTC, snicoll requested changes
I've realized that the maven customizer for devtools hardcode "devtools". That wasn't the intention. If we have several dependencies that need the same customizations, we should try to run the same codepath.

2023-05-24 07:54 UTC, mhalbritter commented
I force pushed with the changes.

2023-05-24 11:15 UTC, closed without merging